services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./IDPLig_app:/app
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env

volumes:
  mongodb_data:
    driver: local
